### ISSUE TITLE
Error when trying to load Main.hs.

### ISSUE THREAD

**Issue by wpoosanguansit** [jml/servant-template#23]
Hi,

After a long stack compile pulling down the libs, I ran into the following error when I do :l Main on the repl.  Thanks for your help.

Server/Instrument.hs:66:25: error:

• Couldn't match expected type ‘Int’ with actual type ‘Integer’
    • In the second argument of ‘recordResult’, namely
        ‘(500 :: Integer)’
      In the second argument of ‘onException’, namely
        ‘recordResult start (500 :: Integer)’
      In a stmt of a 'do' block:
        app
          req
          (\ res
             -> do { recordResult
                       start (HTTP.statusCode (Wai.responseStatus res));
                     respond res })
        `onException` recordResult start (500 :: Integer)

When I do stack install, there is the following error in server-0.1.0...

<no location info>: error: 
Failing due to -Werror.

**Comment by jml** [comment]
Sorry about that. Should be fairly easy to fix. I won't have the chance to look into this for at least a month.

**Comment by wpoosanguansit** [comment]
Thank you for your help.  That is not a problem at all.  Actually, I am just learning how to work with Servant from your code.  Please continue your great work.  Cheers!

**Comment by wpoosanguansit** [comment]
Also, I hope you do not mind I ask a somewhat related question about another error here.  I do get 

Nat
        :: (Handler msg1 a0 -> ExceptT ServantErr IO a0)
           -> Handler msg :~> ExceptT ServantErr IO

in /Handlers.hs:39:22.  What do I need to bring in to satisfy the requirement?  Thanks for your help.

**Comment by jml** [comment]
Sorry, don't know. Perhaps ask on StackOverflow?

**Comment by wpoosanguansit** [comment]
The error is related to this code:

-- | Translate our custom monad into a Servant handler.
--
-- See http://haskell-servant.readthedocs.io/en/stable/tutorial/Server.html#using-another-monad-for-your-handlers
-- for the details.
toHandler
  :: Pretty msg
  => Severity -> (Handler msg :~> ExceptT ServantErr IO)
toHandler logLevel = Nat toHandler'
  where
    toHandler'
      :: Pretty msg
      => Handler msg a -> ExceptT ServantErr IO a
    toHandler' = ExceptT . Log.withLogging logLevel . runExceptT

I followed the link and there doesn't seem to be Nat but NT which is Natural Transformation typeclass.  I tried NT but that didn't seem to work either.  Would you mind sharing how did you code this part of the Handler.hs?  Did you follow a tutorial somewhere that I can check on?  Could it possibly be a version change for some of the lib I included.  Appreciate your help.

**Comment by wpoosanguansit** [comment]
I fixed the issue with:

type Handler' msg = Log.LogM msg IO

toHandler' :: Pretty msg => Severity -> (Handler' msg :~> Servant.Handler)
toHandler' logLevel = NT (Servant.Handler . toHandler''')
  where
    toHandler''' :: Pretty msg => Handler' msg a -> ExceptT ServantErr IO a
    toHandler''' = ExceptT . try . Log.withLogging logLevel

**Comment by jml** [comment]
Thanks for sharing the fix with everyone else!
